import Navbar from "@/Components/Navbar";
import { Inter } from "next/font/google";
import './globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        {children}
        <footer className="container mx-auto bg-gray-400 p-2">
          <p className="text-center">This is footer</p>
        </footer>
      </body>
    </html>
  );
}
